title: Pankis de Mierda
description: Un fanzine de mierda hecho desde África

url: "https://pankisdemierda.github.io"
baseurl: ""

header_pages:
  - index.md
  - about.md

footer: 'Pankis de Mierda'

plugins:
  - jekyll-seo-tag

style: hacker
listen_for_clients_preferred_style: false
